### ISSUE TITLE
How can I use it in my tool

### ISSUE THREAD

**Issue by morpheuslord** [TheBATeam/MenuBar-Function-1.0-by-Kvc#1]
I want to make a interactive gui listing mechanism using your tool but I didn't find any tutorial in your youtube channel on how we can interpret the input like clicking the button into an output like listing out the contents I wanted to list out can you help on how I can do that

**Comment by TheKvc** [comment]
You can combine usage of Button fn 2.0 and Menubar 2.0 together with Getinput.exe plugin. So, all the elements on screen will be clickable by getinput.exe 

I have noted your suggestion - I might work on a YT tutorial regarding that. :) thank you for reaching out to me.

**Comment by morpheuslord** [comment]
ok and thanks a lot
